### ISSUE TITLE
astral issue

### ISSUE THREAD

**Issue by dhruvbalwada** [GliderToolsCommunity/glidertools-demo#1] opened 2021-05-12 15:41 UTC
Wow, these notebooks look amazing!!! 

I was able to run through and get almost everything to work on Binder. Except the last two code cells in the Optics (Quenching correction and Wrapper function), which spit out the error "ModuleNotFoundError: No module named 'astral'". 
Maybe this is this an environment file issue?

**Comment by callumrollo** [comment] 2021-05-12 16:23
Hi Drhuv, the astral issue is caused by the sunset bug in GliderTools. There's a fix in PR #44 over there that should fix it https://github.com/GliderToolsCommunity/GliderTools/pull/44

The GliderTools package on PyPI and conda uses astral, but we are switching to skyfield once that has merged. I wrote the notebooks on the assumption that this would be fixed by the time we run the demo. If it's not, I'll delete the last two cells. There was discussion on this in one of the Slack chats

**Comment by callumrollo** [comment] 2021-05-12 16:31
Just tried running the nb with astral added to the environment. Still throws that error. Pretty sure the issue is in GliderTools itself

**Comment by dhruvbalwada** [comment] 2021-05-12 16:57
Thanks for taking a look, I had not realized about the astral issue (have not been paying attention to the discussion around oxygen lately).

**Closed as completed** 2021-11-10 10:02 UTC
